container_name: fado_clients
image: fedml-client
build: ./docker/client
environment:
  - WAIT_HOSTS=10.2.1.0:8890
  - WAIT_HOST_CONNECT_TIMEOUT=360
  - WAIT_SLEEP_INTERVAL=5
  - WAIT_LOGGER_LEVEL=error
  - WAIT_TIMEOUT=60
restart: on-failure
cap_add:
  - NET_ADMIN # Authorize container to change network configurations
command: >-
  sh -c "/app/config_interfaces_clients.sh && /wait && /app/run_clients.sh"
depends_on:
  - "server"
networks:
  - "clients_net"