malicious_clients: 0
benign_clients: 2
clients_per_round: 2

# Training Hyper Parameters
rounds: 50
epochs: 10
batch_size: 64
client_optimizer: adam
learning_rate: 0.001
model: 'get_model.py'

encrypt_comm: true

dataset: femnist

all_data_folder: data/all
partition_data_folder: data/partitions

#network_attack_spec: 'drop'

random_seed: 0

# Hardware

using_gpu: false