version: '3.9'
services:
  server:
    compose-file: server_compose.yaml
  clients:
    compose-file: clients_compose.yaml
  router:
    compose-file: router_compose.yaml
networks:
  server_net:
  clients_net: