container_name: fedml-malicious-client # For each client it will be container_name + client_rank
image: fedml-client
build: ./docker/client
volumes:
  - './certs/:/app/certs/'
  - './config/:/app/config/'
  - './attack/:/app/attack/:rw'
  - './defense/:/app/defense/:rw'
  - './logs/:/app/logs:rw'
  # - './data:/app/data' Data will be different for each client
environment:
  # - FEDML_RANK=<set after hand> Each client will have a unique rank
  - WAIT_HOSTS=172.20.1.0:8890
  - WAIT_HOST_CONNECT_TIMEOUT=360
  - WAIT_SLEEP_INTERVAL=5
  - WAIT_LOGGER_LEVEL=error
restart: on-failure
cap_add:
  - NET_ADMIN # Authorize container to change network configurations
command: >-
  sh -c "ip route del default &&
  ip route add default via 172.10.0.2 &&
  /wait &&
  /app/run_malicious_client.sh"
deploy:
  resources:
    reservations:
      devices:
        - capabilities: [gpu]
networks:
  clients_network:
    ipv4_address: 172.10.1.0 # Use different addresses for each client