container_name: fado_router
image: fado-router
build: ./docker/router
cap_add:
  - NET_ADMIN # Authorize container to change network configurations
command: >-
  sh -c "/app/apply_nat.sh && /app/run_router.sh"
deploy:
  placement:
    constraints:
      - node.role == manager
networks:
  clients_network:
  server_network:
sysctls:
  - net.ipv4.ip_forward=1 # Enable linux kernel packet forwarding