container_name: fado_router
image: fado-router
build: ./docker/router
volumes:
  - '~/.fado/config/:/app/config/'
cap_add:
  - NET_ADMIN # Authorize container to change network configurations
command: >-
  sh -c "/app/create_interfaces.sh && /app/run_router.sh"
sysctls:
  - net.ipv4.ip_forward=1 # Enable linux kernel packet forwarding
networks:
  - "server_net"
  - "clients_net"