container_name: fedml-server
image: fedml-client
build: ./docker/client
volumes:
  - './certs/:/app/certs/'
  - './config/:/app/config/'
  - './attack/:/app/attack/:rw'
  - './defense/:/app/defense/:rw'
  - './data/all:/app/data'
  - './runs/:/app/runs:rw'
  - './logs/:/app/logs:rw'
cap_add:
  - NET_ADMIN # Authorize container to change network configurations
command: >-
  sh -c "ip route del default &&
  ip route add default via 172.20.0.2 &&
  /app/run_server.sh
  "
deploy:
  resources:
    reservations:
      devices:
        - capabilities: [gpu]
networks:
  server_network:
    ipv4_address: 172.20.1.0