container_name: fedml-server
image: fedml-client
build: ./docker/client
volumes:
  - './certs/:/app/certs/'
  - './config/:/app/config/'
  - './attack/:/app/attack/'
  - './data/partitions/server:/app/data'
cap_add:
  - NET_ADMIN # Authorize container to change network configurations
command: >-
  sh -c "ip route del default &&
  ip route add default via 172.20.0.2 &&
  /app/run_server.sh
  "
networks:
  server_network:
    ipv4_address: 172.20.1.0