container_name: fado_server
image: fedml-client
build: ./docker/client
volumes:
  - '~/.fado/certs/:/app/certs/'
  - '~/.fado/config/:/app/config/'
  - '~/.fado/attack/:/app/attack/:rw'
  - '~/.fado/defense/:/app/defense/:rw'
  #- '~/.fado/data/all:/app/data'
  - '~/.fado/runs/:/app/runs:rw'
  - '~/.fado/logs/:/app/logs:rw'
environment:
  - N_INTERFACES=1
cap_add:
  - NET_ADMIN # Authorize container to change network configurations
command: >-
  sh -c "/app/config_interfaces.sh 2 1 && /app/run_server.sh"
depends_on:
  - "router"