container_name: fado_server
image: fedml-client
build: ./docker/client
volumes:
cap_add:
  - NET_ADMIN # Authorize container to change network configurations
privileged: true
command: >-
  sh -c "/app/config_interfaces_server.sh && /app/run_server.sh"
depends_on:
  - "router"
networks:
  - "server_net"