general:
    random_seed: 0
    use_gpu: true

fl_training_process:
    rounds: 100
    aggregator: mean
    agg_learning_rate: 0.25
    client_optimizer: sgd
    number_clients: 10
    clients_per_round: 2
    num_clients_select: 2
    allow_less_clients: True
    participant_selector: random

client_training_process:
    engine: pytorch
    model: nlafl_emnist_torch
    batch_size: 32
    epochs: 2
    learning_rate: 0.1

attack_args:
    malicious_clients: 0
    target_class: 0
    network:
        remove_pop_clients: 0
        drop_count: 0
    data:
        poison_count: 0
        boost_factor: 0
    model:
        model_attack_name: 'random'

defense_args:
    strategy: clip
    upsample_epoch: 0
    upsample_count: 0

dataset_spec:
    dataset: nlafl_emnist
    dataset_rate: 0.05
    data_distribution: niid
    num_classes: 10
    num_pop_clients: 15
 
communication:
    encrypt_comm: true
    wait_for_clients_timeout: 200

output:
    logs_file_name: "logs_{model}_{target_class}_{num_pop_clients}_{remove_pop_clients}_{drop_count}_{poison_count}_\
    {random_seed}_{strategy}_{boost_factor}_{upsample_epoch}_{upsample_count}"
    results_file_name: "results_{model}_{target_class}_{num_pop_clients}_{remove_pop_clients}_{drop_count}_{poison_count}_\
    {random_seed}_{strategy}_{boost_factor}_{upsample_epoch}_{upsample_count}"

