general:
    random_seed: 0
    use_gpu: true

fl_training_process:
    rounds: 1500
    aggregator: mean
    agg_learning_rate: 0.5
    client_optimizer: sgd
    number_clients: 1000
    clients_per_round: 30
    num_clients_select: 30
    allow_less_clients: True
    participant_selector: random

client_training_process:
    engine: pytorch
    model: mnist_conv_torch
    batch_size: 32
    epochs: 2
    learning_rate: 0.1

attack_args:
    malicious_clients: 0
    target_class: 0
    network:
        remove_pop_clients: 0
        drop_count: 0
    data:
        poison_count_multiplier: 0
        boost_factor: 0
    model:
        model_attack_name: 'random'

dataset_spec:
    dataset: femnist
    #dataset_rate: 0.05
    data_distribution: niid
    num_classes: 62
    num_pop_clients: 15
 
communication:
    encrypt_comm: true
    wait_for_clients_timeout: 200

output:
    logs_file_name: "logs_femnist"
    results_file_name: "results_femnist"

