malicious_clients: 0
benign_clients: 5
clients_per_round: 5

# Training Hyper Parameters
rounds: 100
epochs: 10
batch_size: 64
client_optimizer: adam
learning_rate: 0.1
model: 'get_model.py'

encrypt_comm: true

dataset: femnist
data_dist: niid

data_loader_file: 'data_loader.py'

all_data_folder: data/all
partition_data_folder: data/partitions
#target_class: 1

#network_attack_spec: 'drop'

random_seed: 0

# Hardware

using_gpu: false
