malicious_clients: 0
benign_clients: 1
clients_per_round: 1

# Training Hyper Parameters
rounds: 1
epochs: 1
batch_size: 256
client_optimizer: adam
learning_rate: 0.001

encrypt_comm: true

dataset: femnist
data_dist: niid

data_loader_file: 'data_loader.py'

all_data_folder: data/all
partition_data_folder: data/partitions

#network_attack_spec: 'drop'

random_seed: 0

# Hardware

using_gpu: true