malicious_clients: 0
benign_clients: 10
clients_per_round: 5

# Training Hyper Parameters
rounds: 20
epochs: 10
batch_size: 64
client_optimizer: adam
learning_rate: 0.001

encrypt_comm: true

dataset: cifar10

data_loader: 

all_data_folder: data/all
partition_data_folder: data/partitions
random_seed: 0

# Hardware

using_gpu: true