general:
    random_seed: [3,4,5,6,7]
    use_gpu: false

fl_training_process:
    rounds: 305
    aggregator: mean
    agg_learning_rate: 0.25
    client_optimizer: sgd
    number_clients: 60
    clients_per_round: 10
    num_clients_select: 10
    allow_less_clients: True
    participant_selector: random

client_training_process:
    engine: tensorflow
    model: nlafl_fashionmnist_tf
    batch_size: 32
    epochs: 2
    learning_rate: 0.1

attack_args:
    malicious_clients: 0
    target_class: [0,1,9]
    network:
        network_attack: nlafl
        drop_count_multiplier: 1
        drop_start: 30
    model:
        model_attack_name: 'nlafl_poison'
        poison_count_multiplier: 1
        boost_factor: 10.0

defense_args:
    server:
        server_defense_name: clip
        clip_norm: 1

dataset_spec:
    dataset: nlafl_fashionmnist
    num_classes: 10
    num_pop_clients: 15
 
communication:
    encrypt_comm: true
    wait_for_clients_timeout: 10

output:
    logs_file_name:     "logs_nlafl_fashionmnist_tf_drop_clip_{target_class}_{num_pop_clients}_{random_seed}"
    results_file_name:  "results_nlafl_fashionmnist_tf_drop_clip_{target_class}_{num_pop_clients}_{random_seed}"
    table_round: 300
