general:
    random_seed: 0

fl_training_process:
    rounds: 100
    aggregator: mean
    agg_learning_rate: 0.25
    client_optimizer: sgd
    number_clients: 100
    clients_per_round: 10
    num_clients_select: 10
    participant_selector: random

client_training_process:
    model: nlafl_emnist
    batch_size: 64
    epochs: 10
    learning_rate: 0.1
    using_gpu: false

attack_args:
    malicious_clients: 0
    poison_count: 0
    num_pop_clients: 15
    target_class: 0

dataset_spec:
    dataset: nlafl_emnist
    dataset_rate: 0.05
    data_distribution: niid
    num_classes: 10
    data_loader_file: data_loader.py
 
communication:
    encrypt_comm: true
    wait_for_clients_timeout: 200
