malicious_clients: 0
benign_clients: 50
clients_per_round: 5

# Training Hyper Parameters
rounds: 20
epochs: 10
batch_size: 64
client_optimizer: adam
learning_rate: 0.001

encrypt_comm: true

dataset: femnist
data_dist: niid

all_data_folder: data/all
partition_data_folder: data/partitions

#network_attack_spec: 'drop'

random_seed: 0

# Hardware

using_gpu: true