malicious_clients: 0
benign_clients: 5
clients_per_round: 3
rounds: 100
epochs: 2
batch_size: 20

encrypt_comm: true

dataset: shakespeare

all_data_folder: data/all
partition_data_folder: data/partitions

model_file: get_model.py
random_seed: 0
