malicious_clients: 0
benign_clients: 10
clients_per_round: 5
rounds: 30
epochs: 1
batch_size: 20

encrypt_comm: true

dataset: femnist

all_data_folder: data/all
partition_data_folder: data/partitions

model_file: get_model.py
random_seed: 0
