malicious_clients: 0
benign_clients: 3
clients_per_round: 3
rounds: 50
epochs: 1
batch_size: 10

encrypt_comm: true

model_file: get_model.py

#attack_spec: 'byzantine'
#defense_spec: 'krum'

random_seed: 0
