common_args:
  training_type: cross_silo
  scenario: horizontal
  using_mlops: false
  random_seed: 0
  config_version: local
environment_args:
  bootstrap: config/bootstrap.sh
data_args:
  dataset: mnist
  data_cache_dir: ./data
  partition_method: hetero
  partition_alpha: 0.5
model_args:
  model: lr
  model_file_cache_folder: ./model_file_cache
  global_model_file_path: ./model_file_cache/global_model.pt
train_args:
  federated_optimizer: FedAvg
  client_id_list: null
  client_num_in_total: 4
  client_num_per_round: 4
  comm_round: 50
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
validation_args:
  frequency_of_the_test: 5
device_args:
  worker_num: 2
  using_gpu: false
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default
comm_args:
  backend: GRPC
  grpc_ipconfig_path: ./config/grpc_ipconfig.csv
  grpc_trusted_ca: ./certs/ca-cert.pem
  grpc_certificate: ./certs/server-cert.pem
  grpc_private_key: ./certs/server-key.pem
  check_tls_name: false
tracking_args:
  local_log_output_path: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a619e63fb1f8408
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg_mnist_lr
