#!/bin/bash

# estas cenas é só para nós testarmos...

# alias path_to_fado_experiment=$(pwd) -> while on the experiment folder
# chmod u+x fado.sh
# export PATH=$PATH:$(pwd)
cd /mnt/SSD/filipedfr/warriorsfl/FADO/src/examples/basic
python fado_run.py  "$@"